sudo: required

services:
  - docker

script:
  - docker-compose build
  - docker-compose up -d
  - sleep 5s && ./setup.sh
  - docker-compose restart
  - sleep 5s && curl -i http://localhost:8080
  - docker-compose down
  - docker volume rm ttrssdocker_ttrss ttrssdocker_pgdata
