sudo: required

services:
  - docker

before_install:
  - docker-compose build

install:
  - docker-compose up -d
  - sleep 5s && ./setup.sh
  - docker-compose restart

script:
  - sleep 5s
  - curl -I http://localhost
  - curl -I http://localhost/config.php | grep 403
  - curl -I http://localhost/cache | grep 403
  - curl -I http://localhost/cache/ | grep 403

after_script:
  - docker-compose down
  - docker volume rm ttrssdocker_ttrss ttrssdocker_pgdata
