version: "3"

services:
  caddy:
    image: ghcr.io/sashkab/docker-caddy2/docker-caddy2:latest
    restart: always
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ttrss:/app
      - caddy2:/caddy
      - ./rss/config.php:/app/config.php
    links:
      - phpfpm
    depends_on:
      - phpfpm
    ports:
     - "80:80"
     - "443:443"
    logging:
      options:
        max-size: "100k"
        max-file: "3"


  phpfpm:
    image: ghcr.io/sashkab/ttrss-docker/ttrss-docker:latest
    restart: always
    volumes:
      - ttrss:/app
      - ./rss/config.php:/app/config.php
    links:
      - postgres
    depends_on:
      - postgres
    command: /usr/bin/run.sh
    expose:
      - "9000"
    logging:
      options:
        max-size: "100k"
        max-file: "3"


  update_daemon:
    image: ghcr.io/sashkab/ttrss-docker/ttrss-docker:latest
    restart: always
    volumes:
      - ttrss:/app
      - ./rss/config.php:/app/config.php
    depends_on:
      - postgres
    links:
      - postgres
    command: /usr/bin/update.sh
    logging:
      options:
        max-size: 2m
        max-file: "2"


  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: ttrss
      POSTGRES_PASSWORD: ttrss
      POSTGRES_DB: ttrss
    volumes:
      - pgdata:/var/lib/postgresql/data
#      - ./postgres/postgresql.conf:/var/lib/postgresql/data/postgresql.conf

volumes:
  pgdata:
  ttrss:
  caddy2:
