version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ttrss:/app
      - ./rss/config.php:/app/config.php
    links:
      - phpfpm
    depends_on:
      - phpfpm
    ports:
     - "8080:80"
     - "8443:443"

  phpfpm:
    build:
        context: rss/
        dockerfile: Dockerfile
    restart: always
    volumes:
      - ttrss:/app
      - ./rss/config.php:/app/config.php
    links:
      - postgres
    depends_on:
      - postgres
    command: /usr/sbin/php-fpm7 --nodaemonize
    expose:
      - "9000"

  update_daemon:
    build:
        context: rss/
        dockerfile: Dockerfile
    restart: always
    volumes:
      - ttrss:/app
      - ./rss/config.php:/app/config.php
    depends_on:
      - postgres
    links:
      - postgres
    command: sudo -u ttrss bash -c "sleep 10 && /usr/bin/php7 /app/update_daemon2.php"

  postgres:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_USER: ttrss
      POSTGRES_PASSWORD: ttrss
      POSTGRES_DB: ttrss
    volumes:
      - pgdata:/var/lib/postgresql/data
#      - ./postgres/postgresql.conf:/var/lib/postgresql/data/postgresql.conf

volumes:
  pgdata:
  ttrss:
