version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app:/app
    links:
      - rss
    depends_on:
      - rss
    ports:
     - "8080:80"

  rss:
    image: sashkab/ttrss
    ports:
      - "9000"
    volumes:
      - ./app:/app
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6
    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume:
