version: "3"

services:
  caddy:
    image: docker.pkg.github.com/sashkab/docker-caddy2/docker-caddy2:latest
    restart: always
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ttrss:/app
      - caddy_config:/config
      - caddy_data:/data
      - ./rss/config.php:/app/config.php
    links:
      - phpfpm
    depends_on:
      - phpfpm
    ports:
     - "80:80"
     - "443:443"
    logging:
      options:
        max-size: "100k"
        max-file: "3"


  phpfpm:
    image: docker.pkg.github.com/sashkab/ttrss-docker/ttrss-docker:latest
    restart: always
    volumes:
      - ttrss:/app
      - ./rss/config.php:/app/config.php
    links:
      - postgres
    depends_on:
      - postgres
    command: /usr/sbin/php-fpm7 --nodaemonize
    expose:
      - "9000"
    logging:
      options:
        max-size: "100k"
        max-file: "3"


  update_daemon:
    image: docker.pkg.github.com/sashkab/ttrss-docker/ttrss-docker:latest
    restart: always
    volumes:
      - ttrss:/app
      - ./rss/config.php:/app/config.php
    depends_on:
      - postgres
    links:
      - postgres
    command: sudo -u ttrss bash -c "sleep 10 && /usr/bin/php7 /app/update_daemon2.php"
    logging:
      options:
        max-size: 2m
        max-file: "2"


  postgres:
    image: postgres:12.2-alpine
    restart: always
    environment:
      POSTGRES_USER: ttrss
      POSTGRES_PASSWORD: ttrss
      POSTGRES_DB: ttrss
    volumes:
      - pgdata:/var/lib/postgresql/data
#      - ./postgres/postgresql.conf:/var/lib/postgresql/data/postgresql.conf

volumes:
  pgdata:
  ttrss:
  caddy_config:
  caddy_data:
