version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ttrss:/app
      - ./rss/config.php:/app/config.php
    links:
      - ttrss
    depends_on:
      - ttrss
    ports:
     - "8080:80"

  ttrss:
    build:
        context: rss/
        dockerfile: Dockerfile
    restart: always
    volumes:
      - ttrss:/app
      - ./rss/config.php:/app/config.php
    links:
      - postgres

  postgres:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_USER: ttrss
      POSTGRES_PASSWORD: ttrss
      POSTGRES_DB: ttrss
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  ttrss:
